import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { Analytics } from "@vercel/analytics/react";
import { getServerSession } from 'next-auth';

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EMS",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en" className={montserrat.className}>
      <body className="flex h-screen">
        <Sidebar session={session} />
        <main className="flex-1 overflow-y-auto">
          {children}
        </main>
        <Analytics />
      </body>
    </html>
  );
}
